### ISSUE TITLE
Windows: Hook always passes when running through Powershell or cmd.exe

### ISSUE THREAD

**Issue by dchengTSC** [pre-commit/mirrors-clang-format#11]
I am trying to roll out pre-commit to my mac+windows dev team so we can use clang-format to normalize our coding style. Everything works great on the mac side, but there are a few issues on the Windows side.

Running `pre-commit run --all-files` from Powershell always passes, even if clang-format corrections are needed. The same happens if I run from cmd.exe. Digging into this a bit further, is looks like `where clang-format` outputs `C:\Users\username\AppData\Local\Programs\Python\Python39\Scripts\clang-format.exe`. Running that clang-format.exe directly with the `--version` flag correctly outputs the version from both powershell and cmd.exe.

Interestingly, if I run from git bash (minGW with mintty), it correctly outputs "Failed" along with "files were modified by this hook".

My `.pre-commit-config.yaml` looks like this:
```
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v12.0.1
  hooks:
  - id: clang-format
```

Steps:
* Install Python (I have Python 3.9.6)
* `pip install pre-commit`
* Add or modify a cpp file that has improper formatting
* Run `pre-commit run --all-files` from Powershell or cmd.exe

Expected:
* Output is "Failed" along with "files were modified by this hook"

Actual:
* Output is always "Passed"

**Comment by dokempf** [comment]
Thanks for reporting! This seems to be an incarnation of https://bugs.python.org/issue19124 as `os.execv` is used in the `clang-format` Python package (see https://github.com/ssciwr/clang-format-wheel/blob/main/clang_format/__init__.py#L7) and produces a `0` return code in the scenarios you describe. So, this seems more of an issue of https://github.com/ssciwr/clang-format-wheel - would you mind posting the bug report over there?

**Comment by dchengTSC** [comment]
Got it, will do!

**Comment by dchengTSC** [comment]
Created https://github.com/ssciwr/clang-format-wheel/issues/23

**Comment by dchengTSC** [comment]
@dokempf Thank you for fixing both https://github.com/ssciwr/clang-format-wheel/issues/23 and https://github.com/ssciwr/clang-format-wheel/issues/22 !

I might be missing something, but it looks like we may need a new tag in [mirrors-clang-format](https://github.com/pre-commit/mirrors-clang-format) to point to the updated 12.0.1.1. Here's my `.pre-commit-config.yaml`:

```
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v12.0.1
  hooks:
  - id: clang-format
```

If I leave this as-is, I get the same error as before (I expected this). It looks like I want rev `v12.0.1.1` because I want https://pypi.org/project/clang-format/12.0.1.1/ ... but there isn't an actual tag in [mirrors-clang-format](https://github.com/pre-commit/mirrors-clang-format).

Also FYI: I tried `v13.0.1` for rev and it ran without any of the missing dll problems.

**Comment by dokempf** [comment]
Yes, I am already aware of that. I have reported this here: https://github.com/pre-commit/pre-commit-mirror-maker/issues/123, but Unfortunately, I am not yet sure how to fix this.

**Comment by dokempf** [comment]
@dchengTSC I have re-enabled our own non-automatically mirror hook repository at https://github.com/ssciwr/clang-format-hook

**Comment by dokempf** [comment]
Oh no, what an annoying oversight - that will require retagging all the releases. Glad it works for you though.
