### ISSUE TITLE
Any chance to see clang-tidy as well?

### ISSUE THREAD

**Issue by HappyCerberus** [pre-commit/mirrors-clang-format#13]
This repo hooked me on using pre-commit CI however, I also need clang-tidy (to enforce code style, CamelCase, length of identifiers and such).

The other repositories with C++ hooks don't work with pre-commit CI and after talking with the pre-commit author, there is no way to pull in system packages.

**Comment by asottile** [comment]
let's continue the discussion here!  https://github.com/ssciwr/clang-format-wheel/issues/32
