### ISSUE TITLE
clang-format-wheel 14.0.0 is available

### ISSUE THREAD

**Issue by martin-eder-zeiss** [pre-commit/mirrors-clang-format#14]
Please create a release for clang-format-wheel 14.0.0

**Comment by asottile** [comment]
you don't need to make an issue -- there's a periodic task which will automatically do this

**Comment by jeevcat** [comment]
@asottile v15.0.0 is available, and it seems [the periodic task no longer runs due to repo inactivity](https://github.com/pre-commit/mirrors-clang-format/actions/workflows/main.yml).

**Comment by dokempf** [comment]
@jeevcat The Python distribution for 15 is not yet ready: https://github.com/ssciwr/clang-format-wheel/issues/49
