### ISSUE TITLE
15.0.4 doesn't work on ARM64 Macs.

### ISSUE THREAD

**Issue by Cyberbeni** [pre-commit/mirrors-clang-format#20]
I am getting the following error: `dyld[3244]: Library not loaded: '/usr/local/opt/zstd/lib/libzstd.1.dylib'`

`/usr/local/` is where Homebrew installs stuff on x64, on ARM64, it is `/opt/homebrew/`: https://github.com/Homebrew/install/blob/684032061383ab14862240aaff4273cde4e1847c/install.sh#L129-L138

But to my understanding, it shouldn't try to load globally isntalled libraries.

**Comment by dokempf** [comment]
Can you please open a respective issue at https://github.com/ssciwr/clang-format-wheel? It is where the actual packaging happens.

**Comment by threecgreen** [comment]
[Looks like this is fixed and a 15.0.6 is now available on PyPI](https://github.com/ssciwr/clang-format-wheel/issues/56#issuecomment-1352034924)
