### ISSUE TITLE
InvalidManifestError for revision v16.0.0`

### ISSUE THREAD

**Issue by jannikmi** [pre-commit/mirrors-clang-format#23]
Pointing to the latest revision `v16.0.0`:
 
```
   -   repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v16.0.0
        hooks:
            -   id: clang-format
```

Gets me this error:
```
An error has occurred: InvalidManifestError: 
==> File <>/.cache/pre-commit/repo_x8b3far/.pre-commit-hooks.yaml
==> At Hook(id='clang-format')
==> At key: types_or
==> At index 9
=====> Type tag 'textproto' is not recognized.  Try upgrading identify and pre-commit?
Check the log at <>/.cache/pre-commit/pre-commit.log
make: *** [hook] Error 1
```

with the older revision everything works as expected:
```

    -   repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v15.0.7
        hooks:
            -   id: clang-format
```

**Comment by asottile** [comment]
have you tried what the error message tells you to do?

**Comment by ShaharHD** [comment]
Have the same issue.

```
pre-commit run
An error has occurred: InvalidManifestError: 
==> File /Users/shahar/.cache/pre-commit/repo56pe_co4/.pre-commit-hooks.yaml
==> At Hook(id='clang-format')
==> At key: types_or
==> At index 9
=====> Type tag 'textproto' is not recognized.  Try upgrading identify and pre-commit?
Check the log at /Users/shahar/.cache/pre-commit/pre-commit.log
```
Seems similar to #23 
Tried the following:
- Removing pre-commit cache folder
- Upgrading to latest pre-commit `v3.2.1`
- Removing and re-installing (including pre-commit the pre-commits on the repo)

clang-format at latest version
```shell
clang-format --version
clang-format version 16.0.0
```

pre-commit at latest version
```shell
pre-commit --version
pre-commit 3.2.1
```

Running on macOS Ventura 13.3

**Comment by asottile** [comment]
why did you only try upgrading pre-commit when the error message says to do something else?

**Comment by ShaharHD** [comment]
> why did you only try upgrading pre-commit when the error message says to do something else?

As I mentioned, I also tried removing pre-commit and it's cache folder (aka "Fresh install").
Issue still persists.

I can even see inside VSCode the failure of the `textproto` based on error
![image](https://user-images.githubusercontent.com/700985/228735825-7f19db4e-0bda-43d0-aa0c-8fb8af47dcbe.png)

**Comment by ShaharHD** [comment]
@asottile - I've upgraded now `identify` as well - and this resolved the issue.

Which is a package pre-commit installed and should have been a requirement somewhere on the project of a minimum version.

**Comment by asottile** [comment]
no
