### ISSUE TITLE
Cannot support NixOS

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit/mirrors-clang-format#26]
This hook will download `.cache/pre-commit/repon0nie2em/py_env-python3.10/lib/python3.10/site-packages/clang_format/data/bin/clang-format` for me. However, My OS is NixOS, which doesn't respect HFS so it must patchelf every program. Inspired by <https://github.com/ntkme/sass-embedded-host-ruby/issues/116>, I `NIX_BINTOOLS=/nix/store/ngh5s155lcm1hwsakrfhla536x9g5v4z-binutils-wrapper-2.40 pre-commit run -a`. It works for <https://github.com/scop/pre-commit-shfmt>, but cannot work for this hook. How to make it work?

**Comment by dokempf** [comment]
You should ask your question here instead: https://github.com/ssciwr/clang-format-wheel.

**Comment by asottile** [comment]
sometimes you have to expect that nix is the problem and not everything else
