### ISSUE TITLE
typo in `.pre-commit-hooks.yaml`

### ISSUE THREAD

**Issue by nrbnlulu** [pre-commit/mirrors-clang-format#28]
```console
An error has occurred: InvalidManifestError: 
==> File /home/nir/.cache/pre-commit/repowg948lm5/.pre-commit-hooks.yaml
==> At Hook(id='clang-format')
==> At key: types_or
==> At index 9
=====> Type tag 'textproto' is not recognized.  Try upgrading identify and pre-commit?
```

**Comment by asottile** [comment]
did you try doing what the error message says? it's not wrong

**Comment by nrbnlulu** [comment]
Ok I can confirm it was identify, sorry... I wonder why won't you update the version of identify at pre-commit?

**Comment by asottile** [comment]
think about it a bit and I'm sure you can think of why that's not a good idea

**Comment by nrbnlulu** [comment]
> think about it a bit and I'm sure you can think of why that's not a good idea


I'm not sure if it is a respectful or arrogant reply but thanks anyways.
