### ISSUE TITLE
Recurring problems with minimum identify version

### ISSUE THREAD

**Issue by dokempf** [pre-commit/mirrors-clang-format#29]
Hey @asottile,

there seems to be a recurring thing with people needing to update `identify` in order to continue using this hook. I don't mind too much personally doing this, but it seems like a source of confusion for a lot of people (they might have never personally opted into using pre-commit and not use Python at all!).

How about the following fix: I add a `clang-format[precommit]` extra that adds the correct version constraint for `identify` and we change the hook to install that extra over plain `clang-format`. Does the pre-commit-mirror machinery accept extras?

Alternatively, I guess a good solution would be that a hook specifies its required `identify` version through a special field in `.pre-commit-hooks.yml` similar to how the `minimum_pre_commit_version` field does for the `pre-commit` version.

Best, @dokempf (maintainer of ssciwr/clang-format-wheel)

**Comment by asottile** [comment]
@dokempf if your users can't read the error message that tells them to upgrade `identify` I don't really think there's anything that can be done

**Comment by asottile** [comment]
> Fair point. But I think a minimum_identify_version solution is clean and follows a precedent.

pre-commit **already produces an error message telling them to upgrade identify** so adding that is unnecessary because **it already happens automatically**

**Comment by asottile** [comment]
> Still, this causes ME work with issues although I am not in a position to fix this.

same -- I am quite annoyed that people cannot read -- and yet there is nothing I can do about it either.  the **user** needs to read the error message and do what it tells them to do

**Comment by adehad** [comment]
Hi there @asottile. I recently ran into this (while using `pipx` so had to run `pipx runpip pre-commit install -U identify`) and I have some suggestions, that I am also happy to contribute:
1. (I don't think you'll like this one) The documentation could perhaps be more clear that these two packages are independent and versions need to be managed separately. https://github.com/pre-commit/pre-commit.com/blob/784b35fcdeab2eb9cf4fec9a774faebc9c954fc5/sections/advanced.md?plain=1#L431
Perhaps a sub-section can be used in the docs, and the error message can provide a link to this. Which I know some users will be more likely to use
2. Perhaps if the message helped visually identify the two packages, it would help users reading the messag eg. 
```diff
--Try upgrading identify and pre-commit?
++Try upgrading 'identify' and 'pre-commit'?
```

**Comment by adehad** [comment]
Understand your frustration.

Perhaps if this, or similar flavoured reports come in, hope you consider supplementing the error message content with a presentation that further improves the the developer to user communication to the growing and diversifying userbase.
